### ISSUE TITLE
Fail to run example from tutorial with latest fluids module

### ISSUE THREAD

**Issue by Trophime** [CalebBell/ht#4]
Hi,
just tried the following example from the tutorial:
```
from ht import *

U = 275 # W/m^2/K
A = 10.82 # m^2
Cp_oil = 1900 # J/kg/K
Cp_steam = 1860 # J/kg/K
m_steam = 5.2 # kg/s
m_oil = 0.725 # kg/s
Thi = 130 # °C
Tci = 15 # °C
Cmin = calc_Cmin(mh=m_steam, mc=m_oil, Cph=Cp_steam, Cpc=Cp_oil)
Cmax = calc_Cmax(mh=m_steam, mc=m_oil, Cph=Cp_steam, Cpc=Cp_oil)
Cr = calc_Cr(mh=m_steam, mc=m_oil, Cph=Cp_steam, Cpc=Cp_oil)
NTU = NTU_from_UA(UA=U*A, Cmin=Cmin)
eff = effectiveness_from_NTU(NTU=NTU, Cr=Cr, subtype='crossflow, mixed Cmax')
Q = eff*Cmin*(Thi - Tci)
Tco = Tci + Q/(m_oil*Cp_oil)
Tho = Thi - Q/(m_steam*Cp_steam)

print(Tco,Tho)
```
I end up with an error:
```
Traceback (most recent call last):
  File "test_ht.py", line 1, in <module>
    from ht import *
  File "/usr/lib/python3/dist-packages/ht/__init__.py", line 25, in <module>
    from . import hx
  File "/usr/lib/python3/dist-packages/ht/hx.py", line 28, in <module>
    from fluids.numerics import horner, newton, ridder, quad, secant, quad, bisect
ImportError: cannot import name 'quad' from 'fluids.numerics' (/usr/lib/python3/dist-packages/fluids/numerics/__init__.py)
```

**Comment by CalebBell** [comment]
Hi,
It looks like a bug due to changes in `fluids` which did not have the corresponding changes released in `ht`. I released a new version and the continuous integration says the tests are passing.

Can you install the latest version of `ht`, 0.1.57, with "pip install ht==0.1.57" and see if the error persists? 
Sincerely,
Caleb

**Comment by Trophime** [comment]
Indeed it turns out to be a fluid version pb.
There is a python-fluids package in Debian/Ubunut but it is 0.1.72 version.
Upgrading the package to fluids 0.1.86 fix the issue.
You can close the issue

Best
C
